import type { ExistingFirebreaks, ProposedFirebreaks } from "./types";

export const existingFirebreaks:ExistingFirebreaks[] = [
  {
    id: 1,
    name: "Spanish Town Road Firebreak",
    path: [
      [18.0234, -76.95],
      [18.0189, -76.9234],
      [18.0145, -76.8967],
      [18.0123, -76.87],
    ],
    type: "road",
    width: 50, // meters
    status: "maintained",
    effectiveness: 85,
    lastMaintained: "2024-11-15",
    priority: "high",
  },
  {
    id: 2,
    name: "Rio Cobre Natural Barrier",
    path: [
      [18.0567, -76.98],
      [18.0456, -76.9567],
      [18.0345, -76.9334],
      [18.0234, -76.91],
    ],
    type: "water",
    width: 80,
    status: "natural",
    effectiveness: 95,
    lastMaintained: "N/A",
    priority: "high",
  },
  {
    id: 3,
    name: "Blue Mountain Ridge Firebreak",
    path: [
      [18.08, -76.72],
      [18.0745, -76.69],
      [18.069, -76.66],
      [18.0635, -76.63],
    ],
    type: "cleared_vegetation",
    width: 30,
    status: "needs_maintenance",
    effectiveness: 60,
    lastMaintained: "2024-08-20",
    priority: "medium",
  },
];

export const proposedFirebreaks: ProposedFirebreaks[] = [
  {
    id: 4,
    name: "Kingston Hills Protection Line",
    path: [
      [18.04, -76.82],
      [18.0345, -76.8],
      [18.029, -76.78],
      [18.0235, -76.76],
    ],
    type: "cleared_vegetation",
    width: 40,
    status: "proposed",
    priority: "critical",
    cost: 250000,
    timeline: "3 months",
    protectedAssets: ["Residential areas", "School", "Hospital"],
  },
  {
    id: 5,
    name: "Portmore Coastal Defense",
    path: [
      [17.97, -76.9],
      [17.96, -76.88],
      [17.95, -76.86],
      [17.94, -76.84],
    ],
    type: "road",
    width: 60,
    status: "proposed",
    priority: "high",
    cost: 180000,
    timeline: "2 months",
    protectedAssets: ["Port facilities", "Industrial zone"],
  },
  {
    id: 6,
    name: "Blue Mountain Access Road",
    path: [
      [18.1, -76.7],
      [18.09, -76.68],
      [18.08, -76.66],
    ],
    type: "road",
    width: 35,
    status: "proposed",
    priority: "medium",
    cost: 120000,
    timeline: "4 months",
    protectedAssets: ["Tourist facilities", "Communication towers"],
  },
];

export const defensibleSpaces = [
  {
    id: 1,
    name: "National Stadium Perimeter",
    center: [18.0193, -76.7865],
    radius: 300,
    type: "critical_infrastructure",
    clearanceLevel: "high",
    status: "maintained",
    assets: ["National Stadium", "Emergency shelter"],
    population: 50000,
  },
  {
    id: 2,
    name: "UWI Campus Protection Zone",
    center: [18.0106, -76.7456],
    radius: 250,
    type: "educational",
    clearanceLevel: "medium", // 50m cleared
    status: "maintained",
    assets: ["University", "Research facilities"],
    population: 15000,
  },
  {
    id: 3,
    name: "Spanish Town Hospital Zone",
    center: [17.9914, -76.9574],
    radius: 200,
    type: "medical",
    clearanceLevel: "high",
    status: "maintained",
    assets: ["Hospital", "Medical facilities"],
    population: 8000,
  },
  {
    id: 4,
    name: "Residential Area A",
    center: [18.03, -76.81],
    radius: 150,
    type: "residential",
    clearanceLevel: "low", // 20m cleared
    status: "needs_improvement",
    assets: ["Housing development"],
    population: 12000,
  },
  {
    id: 5,
    name: "Power Substation",
    center: [18.045, -76.83],
    radius: 100,
    type: "utilities",
    clearanceLevel: "high",
    status: "maintained",
    assets: ["Electrical infrastructure"],
    population: 0,
  },
];

// Water sources for firefighting
export const waterSources = [
  {
    id: 1,
    name: "Rio Cobre",
    lat: 18.0345,
    lng: -76.9334,
    type: "river",
    capacity: "unlimited",
    access: "good",
    status: "operational",
  },
  {
    id: 2,
    name: "Mona Reservoir",
    lat: 18.0156,
    lng: -76.7234,
    type: "reservoir",
    capacity: "50000L",
    access: "excellent",
    status: "operational",
  },
  {
    id: 3,
    name: "Portmore Bay",
    lat: 17.94,
    lng: -76.86,
    type: "bay",
    capacity: "unlimited",
    access: "moderate",
    status: "operational",
  },
];